### ISSUE TITLE
Zoom gets stuck

### ISSUE THREAD

**Issue by WMichaelStone** [fin10/GearBrowser#2]
I like the browser and can even get animated radar from intellicast, but sometimes it gets stuck in zoom mode and I can not get it out without rebooting the watch. It even stays zoomed when switching back to clock face or any other menu.
Gear S3 Frontier

**Comment by Changyong-Jeon** [comment]
I think that it's caused by hardware limitations. the intellicast is too heavy. I will report this issue to tizen platform team.
Thank you.
