### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by BrandonJack1** [fin10/GearBrowser#3]
Couldn't leave a review cause Galaxy apps said I had to purchase to write a review. Anyway. Really like the app. Great job. One suggestion to make this perfect in my opinion is to be able to save passwords for websites. Not sure how hard this would be but that would be amazing!

**Comment by fin10** [comment]
Thank you for your opinion.
Unfortunatly this feature isn't availible to be implement on Gear S2 (Tizen 2.3) because the tizen platform does not support it. I haven't checked on Gear S3 (Tizen 3.0) yet because I don't have it, but it will be supported if the tizen platform supports it.
Thank you!
